### ISSUE TITLE
Representing language-pair-specific Style Preferences

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium#118]
As mentioned on <https://sourceforge.net/p/apertium/mailman/message/37241016/> (documented at https://wiki.apertium.org/wiki/Dialectal_or_standard_variation#Overlapping_variants ) , apertium-nno-nob is using a new style preferences system with a single pipeline serving frillions of preference combinations instead of having to compile a new pipeline per combination. But we need to serve the list of possible preferences switches and some kind of description to the web page (possibly also for display in the terminal?).

The list of available preferences is specific to each mode, so I think it makes sense to have a (generated) file with this info per mode, say in a sister directory to `/modes`, such that when you're running `nob-nno` from the file `/usr/share/apertium/modes/nob-nno.mode`, Apy can find the available preferences for that mode in `/usr/share/apertium/prefs/nob-nno.xml` and give it to the web page.

But preferences can be defined in both pair and generator, we want the union of the ones applicable to the mode.

So one possibility is that we store files with preference descriptions in both packages, and then for each mode, we say which files are are applicable. So for `nob-nno`, `apertium-nno` would have a file `nno.preferences.xml`

```xml
<preferences>
  <preference id="ggj_gg">
    <description lang="nno">byggje → bygge</description>
  </preference>
  <preference id="kj_k">
    <description lang="nno">søkje → søke</description>
  </preference>
</preferences>
```

while apertium-nno-nob has `nob-nno.preferences.xml`

```xml
<preferences>
  <preference id="forskjell_skilnad">
    <description lang="nno">forskjell → skilnad</description>
    <description lang="nob">forskjell → skilnad</description>
  </preference>
</preferences>
```

and modes.xml has a new element after the pipeline that refers to these files:

```xml
<mode name="nob-nno">
    <pipeline>
    </pipeline>
    <preferences>
      <pref path="nob-nno.preferences.xml"/>
      <pref path="nno.preferences.xml"/>
    </preferences>
</mode>
```

Then the Makefile.am in the pair builds `prefs/nob-nno.xml` by concatenating the xml:

```sh
{
    echo '<preferences>'
    echo "$f1" | xmllint --xpath '/preferences/preference' -
    echo "$f2" | xmllint --xpath '/preferences/preference' -
    echo '</preferences>'
}
```

```xml
<preferences>
<preference id="forskjell_skilnad">
    <description lang="nno">forskjell → skilnad</description>
    <description lang="nob">forskjell → skilnad</description>
  </preference>
<preference id="ggj_gg">
    <description lang="nno">byggje → bygge</description>
  </preference>
<preference id="kj_k">
    <description lang="nno">søkje → søke</description>
  </preference>
</preferences>
```

which is installed in `/usr/share/apertium/prefs/nob-nno.xml` and read by Apy which passes it on to the web page.

WDYT?

**Comment by jonorthwash** [comment]
How do these modes get applied again?

**Comment by TinoDidriksen** [comment]
> How do these modes get applied again?

That's detailed in the linked email. In short, via variables like `[<STREAMCMD:SETVAR:kj_k>]` injected into the stream by APy or the apertium wrapper.

**Comment by unhammer** [comment]
@xavivars  would it solve your https://wiki.apertium.org/wiki/User:Xavivars/Overlapping_language_variants ?

**Comment by xavivars** [comment]
We actually have a mess in Catalan related pairs right now, but we already _solved_ (or should I better say _workarounded_) the problem of explosion of combinations when compiling.

* For "language variants", we're following [approach 3 here](https://wiki.apertium.org/wiki/User:Xavivars/Overlapping_language_variants#Multiple_variants_per_entry), so that we currently have 3 different monolingual dictionaries being generated: `cat` (for Catalan from Catalonia), `cat_val_uni` (for Catalan from Valencian universities) and `cat_val_gva` (for Catalan from Valencian Government). `cat-valencia` used to historically refer `cat_val_gva`, but since we added a third variant, now it maps to `cat_val_uni`. 
  * The way this works is it generates 3 _fake_ `.dix` files just before compiling, by transforming the generic one into a dictionary that only contains the specific variant + other ([code here](https://github.com/apertium/apertium/blob/master/scripts/apertium-genvrdix)). As we still haven't added _balearic_ as a variant, this is still under control, but compilation time is way longer than we'd like.
* Recently (2017) there was an orthographic reform that we've mostly applied to the generic dictionaries, except a few words that lost an accent that we still keep when generating (analyzing, both words are recognized, and we had to add a few more CG3 rules to improve disambiguation, as the non-accented words are now ambiguous with other words). 
  * The way this works is by having a "pre-postgeneration" step (we wanted something post bilingual transfer, so we could avoid touching all bilingual dictionaries). That step simply matches full words that have accent and shouldn't have it (example used in [`modes.xml`](https://github.com/apertium/apertium-spa-cat/blob/master/modes.xml#L225) and [the dictionary file itself](https://github.com/apertium/apertium-cat/blob/master/apertium-cat.post-diacritics-nous.dix))
* We also have introduced another _style choice_ recently:  the Valencian Government wanted some cities to be translated always according to their official form (in those cases where the official name is in Spanish, regardless if there's a traditional Catalan name, they wanted to keep being in Spanish for official/legal documentation). However, we want an approach where we use the traditional name for a town/city, regardless of what's official (the same way we say _Londres_ and not _London_).
  * The way this works is with an extra `lrx-proc` file, as this only involves `spa-cat`. In the bidix, we have both translations, and we rely on a bilingual disambiguation to choose which one to pick.
  
 If we had to generate different monolinguals to cover everything, we'd need to compile 6 variations right now (as we don't offer all possible combinations), but it would be great if there was a better, finer-grain way to define this variations.

![image](https://user-images.githubusercontent.com/134083/111869576-811e5500-8980-11eb-8a0c-54145199da7e.png)

That said, I'm not sure to which extent this new features would make dealing with apertium-cat easier (as it is now). But I'd love to hear any simplification proposal.

**Comment by unhammer** [comment]
I'm 99% sure you could solve that all the same way as it's now done in nob→nno, where the dix files mark features rather than norms.

* Instead of 3+ generated Catalan dix files, you would just have one that has ambiguous output, but mark all but one with a tag. So you could have `<e><p><l>ès</l><r>ès<s n="n"/><s n="m"/><s n="sg"/></r></p></e>` as the unmarked default, and then `<e><p><l>és<s n="v:grave_aigu"/></l><r>ès<s n="n"/><s n="m"/><s n="sg"/></r></p></e>` would be for anyone wanting the other accent. 
* If you want to do *generate* pre-2017 stuff as well, you can handle it in the same way. Remove the LR restriction on adeu, but put in a tag `<s n="v:pre2017"/>` (or something more fine-grained if necessary).
* The extra lrx-proc step you have is in the same place that nob→nno now has an extra cg-proc step :) I considered using lrx-proc, but CG already has support for writing rules that read stream variables, which gives more flexibility (Apy can run a single pipeline that supports all variants, reading a preference cookie at the start of the stream, no need to generate one lrx file per preference). 

If there's not *that* much overlap, ie. you can count on two hands how many possible variants you want, it sounds fine to keep the two lrx-proc's after bidix and one .mode pipeline per variant, but I think you'd win a lot by changing the generator to outputting ambiguous forms tagged with features and using cg-proc -g -n to pick the features matching your norm. How much work it'd be to change the cat.dix file depends on how it's organised – with nno.dix, I've been trying to move such style choices into pardefs for some time since I knew we wanted something like this.

**Comment by xavivars** [comment]
Can the extra cg-proc step be added multiple times? (I guess yes, as cg-proc should only remove/select the "flags" it knows about, and leave extra ambiguity for the next step)

I still like the idea of having different files that deal with different things (potentially adding more steps to the pipeline, each of them dealing with specific things) so if there was the possibility of having a file to deal with pre-post2017, another file to deal with how toponyms are handled,... 

In that case, I think at least the pre-post 2017 could be better handled this way (current pre-postgen is kind of hacky, as it happens after the generation process has finished)

**Comment by unhammer** [comment]
> Can the extra cg-proc step be added multiple times? 

Yes, nob-nno_e.mode does this to hardcode some features: https://github.com/apertium/apertium-nno-nob/blob/0d906e3d6a7a56f500f8d56468922e7ffa4f3322/modes.xml#L91-L96 

You could have as many such steps as you want (just run cg-proc with no options until the last step).

Note that this also happens after generation, but we work on delimited lexical units (it's just disambiguating forms of a reading instead of readings of a form …)

**Comment by xavivars** [comment]
Actually, what I meant of the "pre-postgen" happening after generation, what I really meant is it happens "after the apertium stream format has disappeared". It acts with almost _raw_ input, like postgen does (with _marked_ forms with `<a/>` in the monodix).

So this solution is definitely better :)

**Comment by unhammer** [comment]
I'll close since there weren't any major protests. apertium-nno-nob now installs 
`/usr/share/apertium/prefs/nob-nno.xml` 
which contains the preferences for the nob→nno mode. This file is created by merging nob-nno.preferences.xml (from the pair package) with nno.preferences.xml (from the target monopackage), and contains localised descriptions of every preference id.

Newest apy can serve this from the /pairprefs endpoint, e.g.
```
$ curl -s 'https://apy.trigram.no/pairprefs'|jq
{
  "nob-nno": {
    "forskjell_skilnad": {
      "nno": "forskjell → skilnad",
      "eng": "Use 'skilnad' instead of 'forskjell'"
    },
    "samd_einig": {
      "nno": "samd → einig"
    },
…
 ```

I went back on listing `<preferences>` paths in modes.xml – I tried it, but it felt like an unnecessary complication. It was simpler and more understandable to just explicitly list the preferences as make targets ( https://github.com/apertium/apertium-nno-nob/commit/f18d15679bf44c7d346875a5eb047520cf9a44f4 ).
