### ISSUE TITLE
gen-modes paths are not absolute and not quoted

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium#119]
Here's an old mode I had lying around:

    $ cat ~/PREFIX/2021-03-12-biprefs/share/apertium/modes/nob-nno.mode           
    lt-proc -w -e '/home/me/PREFIX/2021-03-12/share/apertium/apertium-nno-nob/nob-nno.automorf.bin' | cg-proc …

here's what the new gen-modes does:

```


$ cat /usr/share/apertium/modes/nob-nno.mode 
lt-proc -w -e nob-nno.automorf.bin | cg-proc nob-nno.seg.rlx.bin | cg-proc -w nob-nno.rlx.bin | apertium-tagger -g $2 nob-nno.prob | apertium-pretransfer | lt-proc -b nob-nno.autobil.bin | cg-proc nob-nno.biprefs.rlx.bin | lrx-proc -m nob-nno.autolex.bin | apertium-transfer -b apertium-nno-nob.nob-nno.t1x nob-nno.t1x.bin | apertium-interchunk apertium-nno-nob.nob-nno.t2x nob-nno.t2x.bin | apertium-postchunk apertium-nno-nob.nob-nno.t3x nob-nno.t3x.bin | lt-proc -b nob-nno.autogen.bin | cg-proc -n -g -w nob-nno.genprefs.rlx.bin | lt-proc -p nob-nno.autopgen.bin   
```

The paths should be single-quoted and absolute.

**Comment by TinoDidriksen** [comment]
Right, forgot about that part. That was actually on purpose, on advise from me, because https://github.com/apertium/apertium/blob/master/apertium/Makefile.am#L538-L544 already knows the absolute path. What I forgot to account for was that mode names don't always match folder names, and after I realized this I further forgot to make sure C++ gen-modes added the path again.

**Comment by TinoDidriksen** [comment]
Turns out mr-martian didn't heed my advise and tried to do it exactly as the old gen-modes, but typoed the check.
